# Generated by Django 2.2.3 on 2019-08-20 18:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=512)),
                ('timestamp', models.DateField(verbose_name=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, max_length=500)),
                ('comments', models.ManyToManyField(blank=True, related_name='related_to', through='app.Comentary', to='app.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=64)),
                ('index_body', models.TextField(max_length=256)),
                ('body', models.TextField(max_length=2048)),
                ('timestamp', models.DateField(verbose_name=datetime.datetime.utcnow)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
                ('comments', models.ManyToManyField(blank=True, related_name='related_to', through='app.Comentary', to='app.News')),
            ],
        ),
        migrations.AddField(
            model_name='comentary',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
        migrations.AddField(
            model_name='comentary',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.News'),
        ),
    ]
