# Generated by Django 2.2.3 on 2019-08-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='static/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='img_file',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_file',
            field=models.FileField(blank=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img_file',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
    ]
