# Generated by Django 2.2.3 on 2019-08-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190822_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img_file',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img_file',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
